### ISSUE TITLE
"Server rejected transaction" Error

### ISSUE THREAD

**Issue by Teraskull** [link-discord/mineflayer-auto-eat#8]
Sometimes the server rejects equipping food, and the error appears, and is not caught.

```
Auto Eat started!
Error: Server rejected transaction for clicking on slot 14, on window [
...
].
    at clickWindow (C:\Users\admin\Desktop\node_modules\mineflayer\lib\plugins\inventory.js:413:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async moveSlotItem (C:\Users\admin\Desktop\node_modules\mineflayer\lib\plugins\inventory.js:434:7)
    at async equip (C:\Users\admin\Desktop\node_modules\mineflayer\lib\plugins\simple_inventory.js:126:5)
Auto Eat stopped!

```

**Comment by link-discord** [comment]
Closing since this has been fixed
