### ISSUE TITLE
`bot.loadPlugin(autoEat)` raises `AssertionError [ERR_ASSERTION]: plugin needs to be a function`

### ISSUE THREAD

**Issue by AkagawaTsurunaki** [link-discord/mineflayer-auto-eat#80]
```typescript
import {loader as autoEat} from "mineflayer-auto-eat"
bot.loadPlugin(autoEat)
autoEat(bot)
```
raises AssertionError 
```
AssertionError [ERR_ASSERTION]: plugin needs to be a function
```
I have known how to fix it, and PR will be submitted soon.

Version info:
`mineflayer-auto-eat`: 5.0.0

**Comment by link-discord** [comment]
You are not supposed to use the plugin this way, you are supposed to do `bot.loadplugin(autoEat)` and that's it.

**Comment by AkagawaTsurunaki** [comment]
Thanks for your reply. However, I edited my code as
```typescript
import {loader as autoEat} from "mineflayer-auto-eat"
import {createBot} from "mineflayer";

const botOption = {
    "host": "127.0.0.1",
    "port": 25565,
    "username": "Test"
}

const bot = createBot(botOption)

bot.once("spawn", () => {
    bot.loadPlugin(autoEat)
});
```
and re-installed the package `mineflayer-auto-eat`
Run the code, the error still happened
```
WORK_DIR\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

AssertionError [ERR_ASSERTION]: plugin needs to be a function
    at EventEmitter.loadPlugin (WORK_DIR\node_modules\mineflayer\lib\plugin_loader.js:16:12)
    at loader (WORK_DIR\node_modules\mineflayer-auto-eat\dist\index.js:5:13)
    at EventEmitter.loadPlugin (WORK_DIR\node_modules\mineflayer\lib\plugin_loader.js:25:7)
    at EventEmitter.<anonymous> (WORK_DIR\test.ts:14:9)
    at Object.onceWrapper (node:events:633:28)
    at EventEmitter.emit (node:events:531:35)
    at Client.<anonymous> (WORK_DIR\node_modules\mineflayer\lib\plugins\game.js:95:9)
    at Client.emit (node:events:531:35)
    at emitPacket (WORK_DIR\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (WORK_DIR\node_modules\minecraft-protocol\src\client.js:112:9) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

```

More information:
- Minecraft 1.20.1 and 1.20.6
- Node.js 20.17.0
- mineflayer-auto-eat 5.0.0
- mineflayer 4.22.0
- npm 10.8.2
